"use client";

import { useState } from "react";
import { CheckCircle2, LockKeyhole, Moon, Settings, ShieldCheck, Sun } from "lucide-react";

export default function BossSettingsPage() {
  const [theme, setTheme] = useState<"light" | "focus">("light");
  const changeTheme = (next: "light" | "focus") => { setTheme(next); document.documentElement.dataset.theme = next; window.localStorage.setItem("mavunoone-theme", next); };
  return <main className="space-y-6 p-4 sm:p-6 lg:p-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-600">Executive preferences</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-black text-slate-900"><Settings className="text-emerald-700" size={30} />Mipangilio ya Boss</h1><p className="mt-2 text-slate-500">Badilisha preferences za kuangalia dashboard bila kugusa system secrets au configuration za Admin.</p></div><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Sun className="text-amber-500" size={22} /><div><h2 className="font-black text-slate-900">Muonekano wa dashboard</h2><p className="text-sm text-slate-500">Chagua muonekano unaokufaa wakati wa kusoma reports.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => changeTheme("light")} className={`rounded-xl border p-4 text-left transition ${theme === "light" ? "border-emerald-500 bg-emerald-50" : "border-slate-200 bg-white hover:border-emerald-300"}`}><Sun className="text-amber-500" size={20} /><p className="mt-3 font-bold text-slate-900">Standard light</p><p className="mt-1 text-xs text-slate-500">Muonekano wa kawaida wa biashara.</p></button><button type="button" onClick={() => changeTheme("focus")} className={`rounded-xl border p-4 text-left transition ${theme === "focus" ? "border-emerald-500 bg-emerald-50" : "border-slate-200 bg-white hover:border-emerald-300"}`}><Moon className="text-emerald-700" size={20} /><p className="mt-3 font-bold text-slate-900">Focus mode</p><p className="mt-1 text-xs text-slate-500">Contrast iliyopunguzwa kwa monitoring ndefu.</p></button></div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-700" size={22} /><div><h2 className="font-black text-slate-900">Usalama wa Boss</h2><p className="text-sm text-slate-500">Settings za system zinabaki kwa Admin/Owner.</p></div></div><div className="mt-5 space-y-3 text-sm"><p className="flex items-start gap-3 rounded-xl bg-emerald-50 p-4 text-emerald-900"><CheckCircle2 className="mt-0.5 shrink-0" size={18} />Unaweza kuona reports, CCTV, fleet, customers na staff overview.</p><p className="flex items-start gap-3 rounded-xl bg-slate-50 p-4 text-slate-700"><LockKeyhole className="mt-0.5 shrink-0" size={18} />Payment secrets, hardware configuration, staff provisioning na backups hazionekani kwenye Boss account.</p></div></section></div></main>;
}
