"use client";

import Link from "next/link";
import { ArrowLeft, ShieldCheck, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";

type StaffUser = { id: number; name: string; email: string; phone: string | null; jobTitle: string | null; role: string; createdAt: string };
const roleLabels: Record<string, string> = { admin: "Admin", owner: "Owner", boss: "Boss", manager: "Manager", cashier: "Cashier", storekeeper: "Storekeeper", machine_operator: "Machine Operator", customer: "Customer" };
const titleLabels: Record<string, string> = { finance: "Finance", operations_manager: "Operations Manager", storekeeper: "Storekeeper", cashier: "Cashier", machine_operator: "Machine Operator", administrator: "Administrator", owner: "Owner", boss: "Boss" };

export default function BossEmployeesPage() {
  const [users, setUsers] = useState<StaffUser[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void fetch("/api/boss/employees").then((response) => response.json()).then((data) => setUsers(data.users ?? [])).finally(() => setLoading(false)); }, []);
  return <main className="min-h-screen bg-[#f7f9f8] px-4 py-6 text-slate-900 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1400px] space-y-6"><Link href="/boss" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><ArrowLeft size={16} /> Rudi Command Center</Link><header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Executive visibility</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-bold tracking-tight text-slate-950"><UsersRound className="text-emerald-600" /> Wafanyakazi</h1><p className="mt-2 text-sm text-slate-500">Muhtasari wa staff accounts na majukumu yao. Boss hawezi kuunda au kubadilisha account hapa.</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-emerald-700"><ShieldCheck size={15} /> Read-only view</p><p className="mt-1 text-2xl font-bold text-emerald-950">{users.length} accounts</p></div></header><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Jina</th><th className="px-5 py-4">Email</th><th className="px-5 py-4">Cheo / permissions</th><th className="px-5 py-4">Tarehe ya kuundwa</th></tr></thead><tbody className="divide-y divide-slate-100">{loading ? <tr><td colSpan={4} className="px-5 py-10 text-center text-sm text-slate-500">Inapakia wafanyakazi...</td></tr> : users.map((user) => <tr key={user.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-bold text-slate-800">{user.name}</td><td className="px-5 py-4 text-sm text-slate-600">{user.email}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${user.jobTitle === "finance" ? "bg-amber-50 text-amber-800" : "bg-slate-100 text-slate-700"}`}>{titleLabels[user.jobTitle ?? ""] ?? roleLabels[user.role] ?? user.role}{user.jobTitle === "finance" && <span className="ml-1 text-[10px] opacity-70">· Manager access</span>}</span></td><td className="px-5 py-4 text-sm text-slate-500">{new Date(user.createdAt).toLocaleDateString("sw-TZ")}</td></tr>)}{!loading && users.length === 0 && <tr><td colSpan={4} className="px-5 py-10 text-center text-sm text-slate-500">Hakuna staff accounts zilizopo bado.</td></tr>}</tbody></table></div></section></div></main>;
}
