"use client";

import { FormEvent, useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { MapPin, Phone, Plus, RefreshCw, Search, Users } from "lucide-react";

const money = (value: number) => `TZS ${Math.round(value).toLocaleString("en-TZ")}`;
const num = (value: unknown) => Number(value ?? 0);

type FarmerForm = { name: string; phone: string; location: string; farmSize: string };
type PurchaseForm = { farmerId: string; productName: string; quantityKg: string; pricePerKg: string; paidAmount: string; paymentMethod: string; paymentReference: string };

export default function FarmersPage() {
  const utils = trpc.useUtils();
  const farmersQuery = trpc.farmers.list.useQuery();
  const createFarmer = trpc.farmers.create.useMutation({ onSuccess: () => { utils.farmers.list.invalidate(); setShowAdd(false); setMessage("Mkulima amehifadhiwa kikamilifu."); } });
  const recordPurchase = trpc.farmers.recordPurchase.useMutation({ onSuccess: () => { utils.farmers.list.invalidate(); setPurchase({ farmerId: "", productName: "", quantityKg: "", pricePerKg: "", paidAmount: "", paymentMethod: "cash", paymentReference: "" }); setMessage("Manunuzi na malipo yamehifadhiwa kwenye ledger."); } });
  const [showAdd, setShowAdd] = useState(false);
  const [search, setSearch] = useState("");
  const [message, setMessage] = useState("");
  const [farmer, setFarmer] = useState<FarmerForm>({ name: "", phone: "", location: "", farmSize: "" });
  const [purchase, setPurchase] = useState<PurchaseForm>({ farmerId: "", productName: "", quantityKg: "", pricePerKg: "", paidAmount: "", paymentMethod: "cash", paymentReference: "" });

  const farmers = farmersQuery.data ?? [];
  const visibleFarmers = useMemo(() => farmers.filter((item) => `${item.farmerNumber} ${item.name} ${item.phone ?? ""} ${item.location ?? ""}`.toLowerCase().includes(search.toLowerCase())), [farmers, search]);
  const totals = farmers.reduce((acc, item) => ({ supplied: acc.supplied + num(item.totalSupplied), paid: acc.paid + num(item.totalPaid), balance: acc.balance + num(item.balance) }), { supplied: 0, paid: 0, balance: 0 });

  const submitFarmer = (event: FormEvent) => { event.preventDefault(); setMessage(""); createFarmer.mutate({ name: farmer.name, phone: farmer.phone || undefined, location: farmer.location || undefined, farmSize: farmer.farmSize ? Number(farmer.farmSize) : undefined }); };
  const submitPurchase = (event: FormEvent) => { event.preventDefault(); setMessage(""); recordPurchase.mutate({ farmerId: Number(purchase.farmerId), productName: purchase.productName, quantityKg: Number(purchase.quantityKg), pricePerKg: Number(purchase.pricePerKg), paidAmount: Number(purchase.paidAmount || 0), paymentMethod: purchase.paymentMethod, paymentReference: purchase.paymentReference || undefined }); };

  return <div className="space-y-6">
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Supplier network</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-bold tracking-tight text-slate-950"><Users className="text-emerald-600" /> Wakulima</h1><p className="mt-2 text-sm text-slate-500">Rekodi manunuzi, deni na malipo ya wakulima kutoka database halisi.</p></div><div className="flex gap-2"><button onClick={() => farmersQuery.refetch()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><RefreshCw size={16} /> Refresh</button><button onClick={() => setShowAdd((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-emerald-700"><Plus size={17} /> Mkulima mpya</button></div></header>
    {message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{message}</div>}
    {(createFarmer.error || recordPurchase.error) && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{createFarmer.error?.message || recordPurchase.error?.message}</div>}
    {showAdd && <form onSubmit={submitFarmer} className="grid gap-4 rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm md:grid-cols-4"><div className="md:col-span-2"><label className="label">Jina kamili</label><input required value={farmer.name} onChange={(e) => setFarmer({ ...farmer, name: e.target.value })} className="input" placeholder="Mfano: Asha Mushi" /></div><div><label className="label">Simu</label><input value={farmer.phone} onChange={(e) => setFarmer({ ...farmer, phone: e.target.value })} className="input" placeholder="07xx xxx xxx" /></div><div><label className="label">Eneo</label><input value={farmer.location} onChange={(e) => setFarmer({ ...farmer, location: e.target.value })} className="input" placeholder="Morogoro" /></div><div><label className="label">Ukubwa (acres)</label><input type="number" min="0" step="0.01" value={farmer.farmSize} onChange={(e) => setFarmer({ ...farmer, farmSize: e.target.value })} className="input" /></div><div className="flex items-end"><button disabled={createFarmer.isPending} className="w-full rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">{createFarmer.isPending ? "Inahifadhi..." : "Hifadhi mkulima"}</button></div></form>}
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Wakulima hai</p><p className="mt-2 text-2xl font-bold text-slate-950">{farmers.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">Mazao yaliyopokelewa</p><p className="mt-2 text-2xl font-bold text-slate-950">{totals.supplied.toLocaleString()} kg</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 shadow-sm"><p className="text-sm text-amber-700">Madeni ya wakulima</p><p className="mt-2 text-2xl font-bold text-amber-950">{money(totals.balance)}</p><p className="mt-1 text-xs text-amber-700">Malipo yaliyosalia</p></div></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h2 className="text-lg font-bold text-slate-950">Orodha ya wakulima</h2><p className="text-sm text-slate-500">Namba ya mkulima ndiyo reference ya malipo na manunuzi.</p></div><div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} className="input pl-9" placeholder="Tafuta jina, simu au namba" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left"><thead><tr className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-500"><th className="px-3 py-3">Mkulima</th><th className="px-3 py-3">Mawasiliano</th><th className="px-3 py-3">Supplied</th><th className="px-3 py-3">Amelipwa</th><th className="px-3 py-3">Deni</th><th className="px-3 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{farmersQuery.isLoading ? <tr><td colSpan={6} className="px-3 py-8 text-center text-sm text-slate-500">Inapakia database...</td></tr> : visibleFarmers.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-3 py-4"><p className="font-bold text-slate-950">{item.name}</p><p className="text-xs font-semibold text-emerald-700">{item.farmerNumber}</p></td><td className="px-3 py-4 text-sm text-slate-600"><p className="flex items-center gap-1"><Phone size={14} /> {item.phone || "—"}</p><p className="mt-1 flex items-center gap-1"><MapPin size={14} /> {item.location || "—"}</p></td><td className="px-3 py-4 text-sm font-semibold">{num(item.totalSupplied).toLocaleString()} kg</td><td className="px-3 py-4 text-sm font-semibold text-emerald-700">{money(num(item.totalPaid))}</td><td className="px-3 py-4 text-sm font-semibold text-amber-700">{money(num(item.balance))}</td><td className="px-3 py-4"><button onClick={() => setPurchase({ ...purchase, farmerId: String(item.id) })} className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-bold text-emerald-700 hover:bg-emerald-50">Nunua / Lipa</button></td></tr>)}{!farmersQuery.isLoading && visibleFarmers.length === 0 && <tr><td colSpan={6} className="px-3 py-8 text-center text-sm text-slate-500">Hakuna wakulima kwenye database.</td></tr>}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Rekodi manunuzi na malipo</h2><p className="mb-4 mt-1 text-sm text-slate-500">Kila entry huingia kwenye farmer payment ledger na kuhesabiwa kwenye deni.</p><form onSubmit={submitPurchase} className="grid gap-4 md:grid-cols-3"><div><label className="label">Mkulima</label><select required value={purchase.farmerId} onChange={(e) => setPurchase({ ...purchase, farmerId: e.target.value })} className="input"><option value="">Chagua farmer number</option>{farmers.map((item) => <option key={item.id} value={item.id}>{item.farmerNumber} · {item.name}</option>)}</select></div><div><label className="label">Zao</label><input required value={purchase.productName} onChange={(e) => setPurchase({ ...purchase, productName: e.target.value })} className="input" placeholder="Mahindi" /></div><div><label className="label">Kiasi (kg)</label><input required type="number" min="0.01" step="0.01" value={purchase.quantityKg} onChange={(e) => setPurchase({ ...purchase, quantityKg: e.target.value })} className="input" /></div><div><label className="label">Bei kwa kg (TZS)</label><input required type="number" min="1" value={purchase.pricePerKg} onChange={(e) => setPurchase({ ...purchase, pricePerKg: e.target.value })} className="input" /></div><div><label className="label">Kiasi kilicholipwa</label><input type="number" min="0" value={purchase.paidAmount} onChange={(e) => setPurchase({ ...purchase, paidAmount: e.target.value })} className="input" placeholder="0" /></div><div><label className="label">Njia ya malipo</label><select value={purchase.paymentMethod} onChange={(e) => setPurchase({ ...purchase, paymentMethod: e.target.value })} className="input"><option value="cash">Cash</option><option value="mpesa">M-Pesa</option><option value="tigopesa">Tigo Pesa</option><option value="bank">Benki</option></select></div><div><label className="label">Reference ya muamala</label><input value={purchase.paymentReference} onChange={(e) => setPurchase({ ...purchase, paymentReference: e.target.value })} className="input" placeholder="Receipt / transaction ID" /></div><div className="flex items-end md:col-span-2"><button disabled={recordPurchase.isPending || farmers.length === 0} className="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700">{recordPurchase.isPending ? "Inahifadhi..." : "Hifadhi purchase & payment"}</button></div></form></section>
    <style jsx>{`.label{display:block;margin-bottom:.35rem;font-size:.75rem;font-weight:700;color:#475569}.input{width:100%;border:1px solid #dbe4e0;border-radius:.75rem;background:#fff;padding:.65rem .8rem;font-size:.875rem;color:#0f172a;outline:none}.input:focus{border-color:#10b981;box-shadow:0 0 0 3px rgba(16,185,129,.12)}`}</style>
  </div>;
}
